
version: '3.1'

services:
  session:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - default
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes

volumes:
  data:

networks:
  default:
    driver: bridge