version: '3.1'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - default
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  default:
    driver: bridge
