name: Analyse

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  analyse:
    runs-on: ubuntu-latest
    env: 
      SPOTIFY_CLIENT_ID: ${{ SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Svelte check
        run: npm run check
      - name: Test
        run: npm run test
