name: Analyse

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Create env
        run: |
          echo SPOTIFY_CLIENT_ID={{ vars.SPOTIFY_CLIENT_ID }} >> .env
          echo SPOTIFY_CLIENT_SECRET={{ secrets.SPOTIFY_CLIENT_SECRET }} >> .env
      - name: Install dependencies
        run: bun install
      - name: Generate prisma client
        run: bunx prisma generate
      - name: Svelte check
        run: bun run check
      # - name: Install playwright dependencies
      #   run: npx playwright install --with-deps
      # - name: Test
      #   run: npm run test
