name: Analyse

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
env: 
  CLIENTID: ${{ vars.SPOTIFY_CLIENT_ID }}
  CLIENTSECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Svelte check
        run: npm run check
      - name: Test
        run: npm run test
