name: Analyse

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Svelte check
        run: npm run check
      - name: Test
        run: npm run test
