name: lint

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Format
        run: bun run format
      - name: Lint
        run: bun run lint
